print("working with strings")

str="apples"
print(str)
print(len(str))
print(str.upper())
print(str.lower())
print(str.isupper())
print(str.islower())
print(str.upper().isupper())
print(str.isalpha())
print("\n")
num="A8398"
print(num)
print(num.isnumeric())
print(num.isalnum())
print(num.find("39"))
print(num.endswith("8"))
print(num.count("8"))
print(num.format("A"))
print(num.isdecimal())
print(num.isidentifier())
a="my name is rijas"
print(a)
print(a.replace("rijas","mkr"))
print(str +" are red")